# Site settings
title: "Clément Jamin, ingénieur R&D indépendant en informatique"
email: YYY@XXX.com
url: https://cjamin.github.io/
description: "Après 6 ans passés à Inria comme ingénieur recherche, durant lesquelles j'ai notamment contribué à la bibliothèque CGAL et à la bibliothèque GUDHI, je travaille actuellement comme ingénieur R&D indépendant en informatique."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: "Clément Jamin"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://fr.linkedin.com/in/clementjamin
  - title: github
    url: https://github.com/cjamin

# Build settings
markdown: kramdown
permalink: pretty
